name: Publish NuGet packages
on:
  push:
    branches:
    - master
jobs:
  PublishNugetPackages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          3.1.x
          6.0.x
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create packages
      run: dotnet pack Packages.sln -o Packages -c Release --version-suffix ${{ github.run_number }}
    - name: Publish packages
      run: dotnet nuget push ./Packages/*.nupkg --source https://nuget.pkg.github.com/Staticsoft/index.json --api-key ${{ secrets.GITHUB_TOKEN }}