name: Run tests
on:
  pull_request:
    branches:
    - master
jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          3.1.x
          6.0.x
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run tests
      run: dotnet test Library.sln